Model Creation

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the dataset
df = pd.read_csv('/Users/bapbap23/Desktop/Patient-No-Show-prediction-/patients_new.csv')

In [6]:
df.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,...,Handcap,SMS_received,No-show,ScheduledHour,AppointmentHour,DaysBetween,ScheduledWeekday,AppointmentWeekday,AppointmentMonth,No-show_numeric
0,2.987250e+13,5642903,F,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,JARDIM DA PENHA,0,1,0,...,0,0,No,18,0,0,4,4,4,0
1,5.589978e+14,5642503,M,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,0,0,...,0,0,No,16,0,0,4,4,4,0
2,4.262962e+12,5642549,F,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,MATA DA PRAIA,0,0,0,...,0,0,No,16,0,0,4,4,4,0
3,8.679512e+11,5642828,F,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,PONTAL DE CAMBURI,0,0,0,...,0,0,No,17,0,0,4,4,4,0
4,8.841186e+12,5642494,F,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,JARDIM DA PENHA,0,1,1,...,0,0,No,16,0,0,4,4,4,0

In [7]:
# Features for the biased model (including potentially biased features)
biased_features = ['Gender', 'Handcap', 'Diabetes', 'Scholarship', 'Age', 'DaysBetween', 'SMS_received', 'ScheduledWeekday', 'AppointmentWeekday', 'AppointmentHour', 'ScheduledHour', 'AppointmentMonth']
X_biased = df[biased_features]
y_biased = df['No-show_numeric']

In [8]:
X_biased = pd.get_dummies(X_biased, columns=['Gender', 'ScheduledWeekday', 'AppointmentWeekday', 'AppointmentMonth'])

In [9]:
# Split the biased dataset into training and testing sets
X_train_biased, X_test_biased, y_train_biased, y_test_biased = train_test_split(X_biased, y_biased, test_size=0.2, random_state=42)

print("Biased data shapes:")
print("X_train_biased:", X_train_biased.shape)
print("X_test_biased:", X_test_biased.shape)
print("y_train_biased:", y_train_biased.shape)
print("y_test_biased:", y_test_biased.shape)

Biased data shapes:
X_train_biased: (88421, 25)
X_test_biased: (22106, 25)
y_train_biased: (88421,)
y_test_biased: (22106,)